---
title: "PA1_template"
author: "EF Shorer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing relevant packages

```{r pkg_installation, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(DT)
library(plotly)
library(lubridate)
library(dygraphs)
library(xts) # To make the convertion data-frame / xts format
```

## Importing data

```{r import_data, cache= TRUE, echo=TRUE}
df_data <- read.csv('activity.csv',header=TRUE)
```

## Preprocessing
```{r preprocessing}


```

## Task 1: Steps per day
```{r steps_table, echo=FALSE, fig.height=3, fig.width=15, warning=FALSE}

df_steps <- df_data %>% group_by(date) %>% summarise(total=sum(steps,na.rm=TRUE),
                                                     mean=mean(steps,na.rm=TRUE),
                                                     median=median(steps,na.rm=TRUE))

datatable(df_steps)
```

```{r steps_hist, echo=FALSE, fig.height=5,fig.width=12,warning=FALSE}
gg_total_steps <- ggplot(df_steps,aes(x=date,y=total)) 
gg_total_steps <- gg_total_steps + geom_histogram(stat='identity') 
gg_total_steps <- gg_total_steps + xlab("Date") + ylab("Total Steps")
gg_total_steps <- gg_total_steps + theme(axis.text.x = element_text(                 size=6, angle=45))
plotly::ggplotly(gg_total_steps)

```

## Task 2: Average daily activity pattern

```{r avg_daily_table, echo=FALSE, warning=TRUE}

df_daily <- df_data %>% group_by(interval) %>% summarise(mean = mean(steps,na.rm=TRUE))

DT::datatable(df_daily)
```
```{r avg_daily_plot, echo=FALSE, warning=TRUE, fig.height=5,fig.width=10}
print("Interval with the highest daily mean steps")
print(df_daily[df_daily$mean==max(df_daily$mean),])

gg_interval <- ggplot(df_daily, aes(x=interval, y=mean)) +
 geom_line() + xlab("Time (mins)") + ylab("Mean Steps") +
        theme(axis.text.x = element_text(size=6, angle=45))
plotly::ggplotly(gg_interval)


```
## Task 3: Imputing missing data
Imputing missing data from mean steps
```{r imputing, echo=FALSE}
print("Total missing days:")
sum(is.na(df_data))
df_daily <- as.data.frame(df_daily)

df_data_imputed <- df_data
for (i in 1:length(is.na(df_data$steps))) {
      if (is.na(df_data[i,'steps'])==TRUE) {
              na_interval <- df_data[i,'interval']
              df_data_imputed[i,'steps'] <- round(df_daily[df_daily$interval==na_interval,'mean'])
      }
}
view(df_data_imputed)
```
```{r hist_imputed}
df_steps_imputed <- df_data_imputed %>% group_by(date) %>% summarise(total=sum(steps,na.rm=TRUE),
                                                     mean=mean(steps,na.rm=TRUE),
                                                     median=median(steps,na.rm=TRUE))

gg_total_steps <- ggplot(df_steps_imputed,aes(x=date,y=total)) 
gg_total_steps <- gg_total_steps + geom_histogram(stat='identity') 
gg_total_steps <- gg_total_steps + xlab("Date") + ylab("Total Steps")
gg_total_steps <- gg_total_steps + theme(axis.text.x = element_text(                 size=6, angle=45))
plotly::ggplotly(gg_total_steps)
```

## Task 4: weekend vs weekday

```{r weekend_vs_weekday}
df_data_imputed$day <- weekdays(as.POSIXct(df_data_imputed$date))

is_weekend <- function(x){
        if (x == 'Saturday' | x=='Sunday'){
                return('Weekend')
        }
        else return('Weekday')
}

df_data_imputed$weekend <- sapply(df_data_imputed$day,is_weekend) %>% as.factor()

df_daily_imputed <- df_data_imputed %>% group_by(interval,weekend) %>% summarise(mean = mean(steps,na.rm=TRUE))


gg_interval_2 <- ggplot(df_daily_imputed, aes(x=interval, y=mean)) +
 geom_line() + xlab("Time (mins)") + ylab("Mean Steps") +
        theme(axis.text.x = element_text(size=6, angle=45)) +facet_wrap(df_daily_imputed$weekend,nrow=2,ncol=1)
plotly::ggplotly(gg_interval_2)

```